sudo: required

services:
  - docker

before_install:
- docker pull base/archlinux
- docker run base/archlinux /bin/sh -c "pacman -Syu --noconfirm; pacman --noconfirm -S arch-install-scripts"

script:
- cd akimasa/ArchDisklessMiner
- bash bootstrap-arch.sh