sudo: required

services:
  - docker
cache:
  directories:
    - /home/travis/pkg/

before_install:
- docker pull base/archlinux
script:
- docker run --privileged -v /home/travis/build/akimasa/ArchDisklessMiner:/root/ -v /home/travis/pkg/:/var/cache/pacman/pkg/ base/archlinux /bin/bash /root/travis.sh