sudo: required

services:
  - docker
cache:
  directories:
    - /home/travis/pkg/

before_install:
- docker pull base/archlinux
- docker run base/archlinux /bin/sh -c "pacman -Syu --noconfirm; pacman --noconfirm -S arch-install-scripts"
script:
- pwd
- ls -R
- docker run --privileged -v /home/travis/build/akimasa/ArchDisklessMiner:/root/ -v /home/travis/pkg/:/var/cache/pacman/pkg/ base/archlinux /bin/bash -c "mkdir /run/shm; bash /root/bootstrap-arch.sh; bash /root/setip.sh"