sudo: required

services:
  - docker

before_install:
- docker pull base/archlinux
- docker run base/archlinux /bin/sh -c "pacman -Syu --noconfirm; pacman -noconfirm -S arch-install-scripts; bash bootstrap-arch.sh"

script:
- echo hoge