sudo: required

services:
  - docker
cache:
  directories:
    - /home/travis/pkg/

before_install:
- docker pull base/archlinux
script:
- pwd
- ls -R
- docker run --privileged -v /home/travis/build/akimasa/ArchDisklessMiner:/root/ -v /home/travis/pkg/:/var/cache/pacman/pkg/ base/archlinux /bin/bash -c "pacman -Syu --noconfirm; pacman --noconfirm -S squashfs-tools; mkdir /run/shm; bash /root/bootstrap-arch.sh; bash /root/setip.sh"
- docker run base/archlinux /usr/bin/mksquashfs /srv/arch/ /root/arch.sfs -e /srv/arch/boot/