#!/bin/bash

build() {
    add_checked_modules '/drivers/net/'
    add_module 'squashfs'
    add_module 'loop'
    add_module 'overlay'

    add_binary "/usr/lib/initcpio/ipconfig" "/bin/ipconfig"
    add_binary "/bin/curl"

    add_runscript
}

help() {
    cat <<HELPEOF
This hook loads the necessary modules for a network boot
HELPEOF
}

# vim: set ft=sh ts=4 sw=4 et:
